version: 2.1

executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  build-app:
    executor: dotnet
    steps:
      - checkout
      - restore_cache:
          keys: 
            - app-build-{{ .Revision }}
      - run:
          name: Build application
          command: |
            cd src/Capstone
            dotnet restore
            dotnet publish -c Release -o ../../App
      - save_cache:
         paths:
           - "App"
         key: app-build-{{ .Revision }}
  
  package-app:
    executor: dotnet
    steps:
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - checkout
      - restore_cache:
          keys: 
            - app-build-{{ .Revision }}
      - run:
          name: Build Docker image
          command: |
            pwd
            echo "Application files:"
            ls -la App

            echo "Building container image"
            docker build --tag=capstone
            docker image ls
      - run:
          name: Publish Docker image
          command: |
            echo "Publishing container image"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 727020537064.dkr.ecr.us-east-1.amazonaws.com
            docker tag capstone:latest 727020537064.dkr.ecr.us-east-1.amazonaws.com/capstone:latest
            docker push 727020537064.dkr.ecr.us-east-1.amazonaws.com/capstone:latest

workflows:
  default:
    jobs:
      - build-app
      - package-app:
          requires: [build-app]

