version: 2.1

executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
  aws:
    docker:
      - image: cimg/aws:2023.09

jobs:
  build-app:
    executor: dotnet
    steps:

      - checkout
      - run:
          name: Build application
          command: |
            cd src/Capstone
            dotnet restore
            dotnet publish -c Release -o ../../App
            cd ~/project
            ls -la
      - persist_to_workspace:
          root: ~/project
          paths:
            - "App/*"
  
  package-app:
    executor: aws
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            pwd
            ls -la
            echo "Application files:"
            ls -la App

            echo "Building container image"
            docker build --tag=capstone .
            docker image ls
#      - run:
#          name: Publish Docker image
#          command: |
#            echo "Publishing container image"
#            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 727020537064.dkr.ecr.us-east-1.amazonaws.com
#            docker tag capstone:latest 727020537064.dkr.ecr.us-east-1.amazonaws.com/capstone:latest
#            docker push 727020537064.dkr.ecr.us-east-1.amazonaws.com/capstone:latest

workflows:
  default:
    jobs:
      - build-app
      - package-app:
          requires: [build-app]

