version: 2.1

executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0

jobs:
  build-app:
    executor: dotnet
    steps:
      - checkout
#      - restore_cache:
#          keys: [app-build]
      - run:
          name: Build application
          command: |
            cd src/Capstone
            dotnet restore
            dotnet publish -c Release -o ../../App
      - save_cache:
         paths:
           - "App"
         key: app-build
  package-app:
    executor: dotnet
    steps:
      - checkout
      - restore_cache:
          keys: [app-build]
      - run:
          name: Package application
          command: |
            pwd
            ls -la
            cd App
            echo "Application files should be in here:"
            la -la

workflows:
  default:
    jobs:
      - build-app
      - package-app:
          requires: [build-app]

